### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by db2dinosaur** [db2dinosaur/wDB2REST#1]
posted by Paul Jansen on the blog comments and transferred here:

Hello James, I tried the tool but I get a unhandeled exception back:

See the end of this message for details on invoking
 just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
 System.NullReferenceException: Object reference not set to an instance of an object.
 at wDB2REST.frmMain.frmMain_Load(Object sender, EventArgs e) in D:\AData\CODE\vb\DB2REST\wDB2REST\frmMain.vb:line 189
 at System.EventHandler.Invoke(Object sender, EventArgs e)
 at System.Windows.Forms.Form.OnLoad(EventArgs e)
 at System.Windows.Forms.Form.OnCreateControl()
 at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
 at System.Windows.Forms.Control.CreateControl()
 at System.Windows.Forms.Control.WmShowWindow(Message& m)
 at System.Windows.Forms.Control.WndProc(Message& m)
 at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
 at System.Windows.Forms.Form.WmShowWindow(Message& m)
 at System.Windows.Forms.Form.WndProc(Message& m)
 at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
 at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
 mscorlib
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2650.0 built by: NET471REL1LAST_B
 CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
—————————————-
wDB2REST
 Assembly Version: 0.0.1.2
 Win32 Version: 1.0.0.0
 CodeBase: file:///C:/Users/A148258/Downloads/wDB2REST/wDB2REST.exe
—————————————-
Microsoft.VisualBasic
 Assembly Version: 10.0.0.0
 Win32 Version: 14.7.2053.0 built by: NET47REL1
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
—————————————-
System
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
—————————————-
System.Core
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
—————————————-
System.Windows.Forms
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
—————————————-
System.Drawing
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
—————————————-
System.Configuration
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2053.0 built by: NET47REL1
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
—————————————-
System.Xml
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
—————————————-
System.Runtime.Remoting
 Assembly Version: 4.0.0.0
 Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
 CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
—————————————-

************** JIT Debugging **************
 To enable just-in-time (JIT) debugging, the .config file for this
 application or computer (machine.config) must have the
 jitDebugging value set in the system.windows.forms section.
 The application must also be compiled with debugging
 enabled.

For example:

When JIT debugging is enabled, any unhandled exception
 will be sent to the JIT debugger registered on the computer
 rather than be handled by this dialog box.

Can you help me on this?

B.r. Paul

**Comment by db2dinosaur** [comment]
Paul Jansen followed this up with:

James, I was able to solve this problem by doing a search in the Microsoft registery for wDB2REST and deleting the Triton register entry in HKEY_CURRENT_USER. After that I was able to start the tool again.

WOrks fine now.

**Comment by db2dinosaur** [comment]
Oops - didn't mean to close that there. Paul provided the following explanation of how the problem occurred:

I added a connection. But I made a mistake and deleted that connection and ended the tool.

After that I started the tool again, and that display this error message.

After deleting the register entry I was able to start the tool again.

**Comment by db2dinosaur** [comment]
There are two problems here:
1. I added a load of comments into the code before publishing it on GitHub, and forgot to rebuild it, making the diagnostic messages slightly less useful. The reported line in the original message is actually a comment.
2. When we create a new connection, we save the details in the registry in the local user Software\DB2Dinosaur\wDB2REST path. As Paul was removing from Software/Triton to resolve, the code rebuild will also have covered this.

Following the rebuild, we were unable to reproduce the problem, and all impacted items have been delivered back to GitHub
